# Generated by Django 3.2.9 on 2022-07-11 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='joindb',
            name='seg_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
