# Generated by Django 3.2.9 on 2022-07-12 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_joindb_seg_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='joindb',
            old_name='DOB',
            new_name='Date_of_Birth',
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='pub_on',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='joindb',
            name='seg_id',
            field=models.PositiveIntegerField(blank=True, help_text='Renewers only !!', null=True),
        ),
    ]
